<script>
	$(document).ready(function() {

		$.fn.preload = function() {
			this.each(function(){
				$('<img/>')[0].src = 'images/' + this;
			});
		}

		$(['termsOfUseOver.jpg']).preload();

	});
</script>
<div id="termsOfUseSeparator"></div>
<div class="clear"></div>
<div id="privacyPolicyText">
	<h1>Terms of use</h1>
	<p>Welcome to our website! Funny-celebs and its associates provide their services to you subject to the following conditions. If you visit or shop within this website, you accept these conditions. Please read them carefully.</p>
	<h2>Privacy</h2>
	<p>Please review our Privacy policy, which also governs your visit to our website, to understand our practices.</p>
	<h2>Electronic communications</h2>
	<p>When you visit Funny-celebs or send e-mails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
	<h2>Copyright</h2>
	<p>All content included on this site, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of Funny-celebs or its content suppliers and protected by international copyright laws. The compilation of all content on this site is the exclusive property of Funny-celebs, with copyright authorship for this collection by Funny-celebs, and protected by international copyright laws.</p>
	<h2>Trade marks</h2>
	<p>Funny-celebs trademarks and trade dress may not be used in connection with any product or service that is not Funny-celebs, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Funny-celebs. All other trademarks not owned by Funny-celebs or its subsidiaries that appear on this site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Funny-celebs or its subsidiaries.</p>
	<h2>License and site access</h2>
	<p>Funny-celebs grants you a limited license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Funny-celebs. This license does not include any resale or commercial use of this site or its contents: any collection and use of any product listings, descriptions, or prices: any derivative use of this site or its contents: any downloading or copying of account information for the benefit of another merchant: or any use of data mining, robots, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of Funny-celebs. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Funny-celebs and our associates without express written consent. You may not use any meta tags or any other "hidden text" utilizing Funny-celebs name or trademarks without the express written consent of Funny-celebs. Any unauthorized use terminates the permission or license granted by Funny-celebs. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the home page of Funny-celebs so long as the link does not portray Funny-celebs, its associates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any Funny-celebs logo or other proprietary graphic or trademark as part of the link without express written permission.</p>
	<h2>Your membership account</h2>
	<p>If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. If you are under 18, you may use our website only with involvement of a parent or guardian. Funny-celebs and its associates reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in their sole discretion.</p>
	<h2>Reviews, comments, emails and other content</h2>
	<p>Visitors may post reviews, comments, and other content: and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. Funny-celebs reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content. If you do post content or submit material, and unless we indicate otherwise, you grant Funny-celebs and its associates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant Funny-celebs and its associates and sublicensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post: that the content is accurate: that use of the content you supply does not violate this policy and will not cause injury to any person or entity: and that you will indemnify Funny-celebs or its associates for all claims resulting from content you supply. Funny-celebs has the right but not the obligation to monitor and edit or remove any activity or content. Funny-celebs takes no responsibility and assumes no liability for any content posted by you or any third party.</p>
	<h2>Risk of loss</h2>
	<p>All items purchased from Funny-celebs are made pursuant to a shipment contract. This basically means that the risk of loss and title for such items pass to you upon our delivery to the carrier.</p>
	<h2>Product descriptions</h2>
	<p>Funny-celebs and its associates attempt to be as accurate as possible. However, Funny-celebs does not warrant that product descriptions or other content of this site is accurate, complete, reliable, current, or error-free. If a product offered by Funny-celebs itself is not as described, your sole remedy is to return it in unused condition.</p>
	<p>DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY THIS SITE IS PROVIDED BY FUNNY-CELEBS ON AN "AS IS" AND "AS AVAILABLE" BASIS. FUNNY-CELEBS MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS SITE OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS SITE. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS SITE IS AT YOUR SOLE RISK. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, FUNNY-CELEBS DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. FUNNY-CELEBS DOES NOT WARRANT THAT THIS SITE, ITS SERVERS, OR E-MAIL SENT FROM FUNNY-CELEBS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. FUNNY-CELEBS WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS SITE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.
	</p>
	<h2>Site policies, modification and severability</h2>
	<p>Please review our other policies, such as our Shipping and Returns policy, posted on this site. These policies also govern your visit to Funny-celebs. We reserve the right to make changes to our site, policies, and these Terms of Use at any time. If any of these conditions shall be deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition.</p>
	<h2>Questions</h2>
	<p>Questions regarding our Terms of Use, Privacy Policy, or other policy related material can be directed to our support staff by clicking on the "Contact" link in the side menu.</p>
</div>
<div class="clear"></div>
<? include('disclaimer.php'); ?>